name: CI-Testing
on: workflow_dispatch
jobs:
  first-job:
     runs-on: ubuntu-latest
     steps: 
         - name: pulling up the code  
           uses: actions/checkout@v6

         - name: Set Up Node 
           uses: actions/setup-node@v4

         - name: Run the nodejs   
           run: npm start

        # uses is used to use our github pre written actions/ use the plugins 
        # run command is used to run your linux command 
