name: CI-Testing
on: push
jobs:
  first-job:
     runs-on: ubuntu-latest
     steps:  
        - name: Print Anish name
          run: echo "ANISH"
        - name: check the file background
          run: ls 
